nelmio_api_doc:
    documentation:
        info:
            title: Study On Billing
            description: Сервис для оплаты курсов
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    models:
        names:
            - { alias: User, type: App\Entity\User }
            - { alias: UserDto, type: App\Model\UserDto }
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
