language: php
php:
  - 7.2

cache:
  yarn: true
  directories:
    - ${HOME}/.composer/cache
    - ./bin/.phpunit

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo chown -R ${UID:-1000}:${GID:-1000} $PWD
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker -v
  - docker-compose -v
  - cp .env.test.local.travis .env.test.local
  - mkdir -p config/jwt
  - openssl genrsa -out config/jwt/private.pem 2048
  - openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php composer install
  - docker-compose exec php bin/console doctrine:database:create --env=test
  - docker-compose exec php bin/console doctrine:migrations:migrate --env=test --no-interaction
  - docker-compose exec php bin/console doctrine:fixtures:load --env=test --no-interaction

script:
  - docker-compose exec php bin/phpunit

after_script:
  - docker-compose down